import { z } from "zod";
import {
  connectionDeviceEnrollmentSchema,
  connectionDeviceGrantSchema,
  connectionHostIdSchema,
} from "@deepseek-ai/dsh-client";

export type DshAccessErrorCode =
  | "browser-auth-required"
  | "runtime-unavailable"
  | "session-unavailable"
  | "session-refresh-failed"
  | "invalid-origin"
  | "invalid-record"
  | "storage-unavailable"
  | "not-paired"
  | "already-paired"
  | "unsupported-platform"
  | "transport-disposed"
  | "request-cancelled"
  | "transport-failed"
  | "invalid-response"
  | "invalid-enrollment"
  | "expired-enrollment"
  | "enrollment-rejected"
  | "enrollment-outcome-unknown"
  | "enrollment-save-failed";

/** Fixed diagnostics keep native errors, stored grants and response bodies out of logs. */
export class DshAccessError extends Error {
  constructor(readonly code: DshAccessErrorCode) {
    super(`dsh-access/${code}`);
    this.name = "DshAccessError";
  }
}

/** Cleartext is confined to the local machine or numeric Tailscale addresses. */
export function parseDshOrigin(value: string): string {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    throw new DshAccessError("invalid-origin");
  }
  const hasExtras =
    url.username !== "" || url.password !== "" || value.includes("?") || value.includes("#");
  if (hasExtras || url.pathname !== "/" || value !== value.trim()) {
    throw new DshAccessError("invalid-origin");
  }
  const secure = url.protocol === "https:";
  const privateHttp = url.protocol === "http:" && isPrivateHost(url.hostname);
  if (!secure && !privateHttp) throw new DshAccessError("invalid-origin");
  return url.origin;
}

function isPrivateHost(host: string): boolean {
  if (host === "localhost" || host === "127.0.0.1" || host === "[::1]") return true;
  if (host.startsWith("[fd7a:115c:a1e0:")) return true;
  const parts = host.split(".").map(Number);
  const isV4 =
    parts.length === 4 && parts.every((part) => Number.isInteger(part) && part >= 0 && part <= 255);
  return isV4 && parts[0] === 100 && parts[1] >= 64 && parts[1] <= 127;
}

const pairingSchema = z
  .object({
    version: z.literal(1),
    origin: z.string(),
    enrollment: connectionDeviceEnrollmentSchema,
  })
  .strict();
export type DshPairing = z.infer<typeof pairingSchema>;

/** Validate untrusted QR data before displaying its endpoint or making any request. */
export function parseDshPairing(value: unknown): DshPairing {
  const result = pairingSchema.safeParse(value);
  if (!result.success) throw new DshAccessError("invalid-enrollment");
  const origin = parseDshOrigin(result.data.origin);
  if (result.data.enrollment.expiresAt <= Date.now())
    throw new DshAccessError("expired-enrollment");
  return { ...result.data, origin };
}

/** QR contents remain in memory; they never enter route parameters or diagnostics. */
export function decodeDshPairing(raw: string): DshPairing {
  if (raw.length > 4096) throw new DshAccessError("invalid-enrollment");
  let value: unknown;
  try {
    value = JSON.parse(raw);
  } catch {
    throw new DshAccessError("invalid-enrollment");
  }
  return parseDshPairing(value);
}

const storedHostSchema = z
  .object({ version: z.literal(1), origin: z.string(), grant: connectionDeviceGrantSchema })
  .strict();
export type StoredDshHost = z.infer<typeof storedHostSchema>;
export function parseStoredDshHost(value: unknown): StoredDshHost {
  const result = storedHostSchema.safeParse(value);
  if (!result.success) throw new DshAccessError("invalid-record");
  return { ...result.data, origin: parseDshOrigin(result.data.origin) };
}

const id = z.string().uuid();
const owner = { ownerId: id };
const socket = { ...owner, socketId: id };
/** Application-owned IPC only; DSH envelopes remain generated by its installed client. */
export const desktopDshCommandSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("list") }).strict(),
  z
    .object({
      type: z.literal("pair"),
      claimId: id,
      pairing: z.unknown(),
      label: z.string().trim().min(1).max(80),
    })
    .strict(),
  z.object({ type: z.literal("cancel-pair"), claimId: id }).strict(),
  z.object({ type: z.literal("forget"), hostId: connectionHostIdSchema }).strict(),
  z.object({ type: z.literal("open"), ...owner, hostId: connectionHostIdSchema }).strict(),
  z.object({ type: z.literal("close"), ...owner }).strict(),
  z
    .object({
      type: z.literal("fetch"),
      ...owner,
      requestId: id,
      url: z.string().max(4096),
      method: z.literal("POST"),
      headers: z.record(z.string(), z.string()),
      body: z.string(),
    })
    .strict(),
  z.object({ type: z.literal("abort"), ...owner, requestId: id }).strict(),
  z.object({ type: z.literal("socket-open"), ...socket, url: z.string().max(4096) }).strict(),
  z.object({ type: z.literal("socket-send"), ...socket, data: z.string() }).strict(),
  z
    .object({
      type: z.literal("socket-close"),
      ...socket,
      code: z.number().int().optional(),
      reason: z.string().optional(),
    })
    .strict(),
]);
export type DesktopDshCommand = z.infer<typeof desktopDshCommandSchema>;
export type DesktopDshReply =
  | { ok: true; value: unknown }
  | { ok: false; error: DshAccessErrorCode };
export const desktopDshHostSchema = z
  .object({ hostId: connectionHostIdSchema, origin: z.string(), label: z.string() })
  .strict();
export type DesktopDshHost = z.infer<typeof desktopDshHostSchema>;
export const desktopDshHostsSchema = z.array(desktopDshHostSchema);
export const desktopDshFetchSchema = z
  .object({ ok: z.boolean(), status: z.number().int(), body: z.unknown() })
  .strict();
export const desktopDshSocketEventSchema = z.discriminatedUnion("type", [
  z.object({ ...socket, type: z.literal("open") }).strict(),
  z.object({ ...socket, type: z.literal("error") }).strict(),
  z.object({ ...socket, type: z.literal("close") }).strict(),
  z.object({ ...socket, type: z.literal("message"), data: z.string() }).strict(),
]);
export type DesktopDshSocketEvent = z.infer<typeof desktopDshSocketEventSchema>;
export interface DesktopDshBridge {
  request(command: DesktopDshCommand): Promise<DesktopDshReply>;
  onSocket(listener: (event: DesktopDshSocketEvent) => void): () => void;
}

/** Native preview operations admitted from the installed DSH registry. */
export const dshSessionEndpoints = [
  "workspace/follow",
  "session/list",
  "session/control",
  "session/follow",
  "session/prompt",
  "session/cancel",
  "subagents/list",
] as const;

/** Optional native history reads; absent operations do not reject basic Session admission. */
export const dshHistoryEndpoints = ["session/page", "session/historyDetail"] as const;

/** Optional native Workspace registration and explicit current-state lookup. */
export const dshRegistrationEndpoints = ["workspace/create", "workspace/resolveByPath"] as const;

/** Optional native Session creation and Host profile catalog. */
export const dshCreationEndpoints = ["session/create", "agentPresets/list"] as const;

/** Optional native Session full-text search; provider activation remains Host-owned. */
export const dshSearchEndpoints = ["session/search"] as const;
